export const actions = {
    LOAD_PRESENT_LIST: 'PATIENTS/LOAD_PRESENT_LIST',
    LOAD_QUITTING_LIST: 'PATIENTS/LOAD_QUITTING_LIST',
    LOAD_PATIENT_INFO: 'PATIENTS/LOAD_PATIENT_INFO',
    MAKE_VIEW_ACTIVE: 'PATIENTS/MAKE_VIEW_ACTIVE'
};